import type { Question, TopicId } from "./types";

export const TOPICS: Record<TopicId, { label: string; short: string; emoji: string; color: string }> = {
  pristup: { label: "Pristup mestu nesreće i bezbednost", short: "Bezbednost", emoji: "🚧", color: "#f59e0b" },
  pregled: { label: "Pregled povređenog i vitalni znaci", short: "Pregled", emoji: "🔎", color: "#38bdf8" },
  kpr: { label: "Reanimacija (KPR) i AED", short: "KPR i AED", emoji: "🫀", color: "#ef4444" },
  disajni: { label: "Disajni put i zagušenje", short: "Disajni put", emoji: "🫁", color: "#a78bfa" },
  krvarenje: { label: "Krvarenja i šok", short: "Krvarenja", emoji: "🩸", color: "#fb7185" },
  povrede: { label: "Povrede, prelomi i opekotine", short: "Povrede", emoji: "🦴", color: "#34d399" },
  stanja: { label: "Iznenadna oboljenja i stanja", short: "Stanja", emoji: "⚡", color: "#facc15" },
  trovanja: { label: "Trovanja, ujedi i ubodi", short: "Trovanja", emoji: "🐍", color: "#22d3ee" },
};

/**
 * BAZA PITANJA — Crveni krst Srbije, test prve pomoći.
 *
 * Izvor: 4 skenirane verzije istog testa (A, B, C, D). Verzije dele brojeve
 * pitanja ali imaju različite formulacije i različit redosled ponuđenih odgovora.
 * Duplikati između verzija su uklonjeni; "blizanci" (isto pitanje, drugačiji
 * set odgovora) nose isti `group` da se ne pojave dvaput u istoj rundi.
 *
 * KAKO DODATI NOVA PITANJA:
 *   1. Dodaj objekat na kraj niza sa NOVIM, jedinstvenim `id` (npr. "e01", "e02"...).
 *   2. `correct` je index tačnog odgovora u nizu `options` (0, 1 ili 2).
 *   3. Ako pitanje već postoji u drugoj formulaciji — daj im isti `group`.
 *   4. NIKADA ne menjaj postojeći `id` — na njega je vezana istorija u bazi.
 */
export const QUESTIONS: Question[] = [
  // ─────────────────────────── VERZIJA A ───────────────────────────
  {
    id: "a01",
    topic: "pristup",
    text: "Dve nedelje nakon pružanja prve pomoći u situaciji teške nesreće, kod spasioca su se pojavili sledeći znaci: podrhtavanje ruku, obilno znojenje, učestalo vraćanje slika nesreće, poremećaj sna, iznenadni napadi plača, razdražljivost. Sve ovo ukazuje na pojavu:",
    options: [
      "Psihičkog oboljenja",
      "Bolesti žlezda sa unutrašnjim lučenjem",
      "Odložene stresogene reakcije nakon pružanja prve pomoći",
    ],
    correct: 2,
  },
  {
    id: "a02",
    topic: "pristup",
    text: "Spasilac nakon pruženih mera prve pomoći i zbrinjavanja unesrećenih lica, na mestu nesreće treba još da:",
    options: [
      "Proceni situaciju vezanu za bezbednost unesrećenih i spasioca",
      "Ukloni upotrebljeni otpadni materijal",
      "Pruži neodložne mere pomoći",
    ],
    correct: 1,
  },
  {
    id: "a03",
    topic: "pristup",
    group: "znak-na-fotografiji",
    visual: "☢️",
    text: "Koji znak je prikazan iznad?",
    options: [
      "Specijalna oznaka za obeležavanje opasne radioaktivne materije",
      "Specijalna oznaka za transport opasnih materija",
      "Specijalna oznaka za opasnost od trovanja",
    ],
    correct: 0,
  },
  {
    id: "a04",
    topic: "pristup",
    text: "Spasilac treba da sagleda postojanje stalne opasnosti, neposredne opasnosti i preteće opasnosti:",
    options: [
      "Dok traje spasavanje",
      "Nakon pružanja mera neodložne pomoći",
      "Pri pristupu mestu nesreće, a pre započinjanja akcije spasavanja",
    ],
    correct: 2,
  },
  {
    id: "a05",
    topic: "pristup",
    group: "voltin-luk",
    text: "Struja visokog napona oslobođena iz oštećenih vodova može u vidu luka (Voltin luk) do čak 18 m da izazove strujni udar. Zato je prva aktivnost spasioca pri nailasku na mesto nesreće:",
    options: [
      "Ne prilaziti do udaljenosti od 9 metara",
      "Pozvati policiju 192",
      "Pozvati nadležnu elektrodistribuciju i, nakon informacije da je dalekovod isključen, pristupiti povređenom uz mere zaštite i dobar izolator",
    ],
    correct: 2,
  },

  // ─────────────────────────── VERZIJA B ───────────────────────────
  {
    id: "b06",
    topic: "pregled",
    group: "primarni-pregled",
    text: "Primarni pregled povređenog podrazumeva proveru:",
    options: [
      "Svih vidljivih povreda",
      "Posedovanja medicinske dokumentacije unesrećenih lica",
      "Svesti, disajnog puta i disanja",
    ],
    correct: 2,
  },
  {
    id: "b07",
    topic: "pregled",
    group: "sekundarni-pregled",
    text: "Sekundarni pregled povređenog podrazumeva:",
    options: [
      "Postojanje velikih rana na telu koje krvare",
      "Pregled tela detaljno primenom tehnike „od glave do pete”",
      "Proveru vitalnih funkcija",
    ],
    correct: 1,
  },
  {
    id: "b08",
    topic: "pregled",
    group: "znaci-simptomi",
    text: "U ZNAKE povreda i bolesti spadaju:",
    options: [
      "Slabost, žeđ, crvenilo, vrtoglavica",
      "Prisustvo krvarenja i deformiteti ekstremiteta",
      "Karakterističan miris, svetlucanje pred očima, bledilo, osećaj mučnine",
    ],
    correct: 1,
    note: "Znaci su ono što spasilac VIDI i izmeri. Simptomi su ono što povređeni OSEĆA i opiše.",
  },
  {
    id: "b09",
    topic: "pregled",
    group: "kaciga",
    text: "Zaštitna kaciga se NE SKIDA kod povređenog u slučaju:",
    options: [
      "Kada disajni put možemo učiniti prohodnim sa kacigom na glavi",
      "Kada motociklista leži na levom boku",
      "Kada motociklista diše brže od 20 ciklusa u minuti",
    ],
    correct: 0,
  },
  {
    id: "b10",
    topic: "pregled",
    text: "Kod zdrave, odrasle osobe, zenice oba oka su:",
    options: [
      "Nejednake, okrugle, ne reaguju na svetlost",
      "Jednake, ukočene, reaguju na svetlost",
      "Jednake, okrugle i sužavaju se na svetlosni snop",
    ],
    correct: 2,
  },
  {
    id: "b11",
    topic: "pregled",
    text: "Elementi za procenu Glazgov koma skale su:",
    options: [
      "Boja usana, izgled lica i pokretljivost",
      "Oči, govor i pokreti",
      "Frekvencija pulsa, nivo krvnog pritiska i temperatura tela",
    ],
    correct: 1,
  },
  {
    id: "b12",
    topic: "pregled",
    group: "zavojni-materijal",
    text: "Šta od navedenog NE SPADA u sterilan zavojni materijal?",
    options: ["Prvi zavoj tip 1", "Prvi zavoj tip 2", "Kaliko zavoj u originalnom pakovanju"],
    correct: 2,
  },
  {
    id: "b13",
    topic: "kpr",
    group: "uzrok-zastoja",
    text: "Najčešći uzrok naglog srčanog zastoja su srčana oboljenja, i tada postoji potreba za izvođenjem mera KPR:",
    options: ["Netačno", "Tačno, ali mere KPR nisu uvek neophodne", "Tačno, i obavezno se primenjuju mere KPR"],
    correct: 2,
  },
  {
    id: "b14",
    topic: "kpr",
    group: "znaci-zastoja",
    text: "Osnovni znaci naglog srčanog zastoja su:",
    options: ["Nagli pad na podlogu", "Nevoljni trzaji ekstremiteta", "Odsustvo svesti i disanja"],
    correct: 2,
  },
  {
    id: "b15",
    topic: "kpr",
    group: "odnos-kompresija",
    text: "Kompresije grudnog koša i veštačko disanje kod ODRASLE osobe se rade u odnosu (kompresija grudnog koša : ventilacija pluća):",
    options: ["15:1", "30:2", "5:1"],
    correct: 1,
  },
  {
    id: "b16",
    topic: "kpr",
    group: "brzina-masaze",
    text: "Spoljašnja masaža srca izvodi se ritmično, brzinom od 100 do 120 u minutu, a unesrećeni treba da:",
    options: ["Bude na postelji", "Se ne pomera sa mesta nesreće", "Leži na čvrstoj podlozi"],
    correct: 2,
  },
  {
    id: "b17",
    topic: "kpr",
    group: "polozaj-glave",
    text: "U koji položaj treba postaviti glavu ODRASLE osobe bez sumnje na povredu vratne kičme kod veštačkog disanja?",
    options: ["U neutralan položaj", "Zabačenu unazad", "Zatečeni položaj"],
    correct: 1,
  },
  {
    id: "b18",
    topic: "kpr",
    group: "aed-funkcije",
    text: "Osnovne dve funkcije AED aparata su analiziranje srčanog ritma i isporuka elektrošokova, a koriste ga:",
    options: [
      "Profesionalci obučeni za rad sa tom vrstom AED-a",
      "Svako lice koje poznaje tehniku primene — laici",
      "Specijalno obučeni pripadnici vatrogasne službe i policije",
    ],
    correct: 1,
  },
  {
    id: "b19",
    topic: "kpr",
    group: "aed-elektrode",
    text: "Kod odrasle osobe elektrode AED aparata se postavljaju na gornji desni ugao grudnog koša ispod ključne kosti i pored leve bradavice s bočne strane grudnog koša, pri čemu vodimo računa da:",
    options: [
      "Grudni koš bude oslobođen malja i znoja/vlage",
      "Skinemo nakit sa vrata pre postavljanja elektroda",
      "Elektrode budu spojene jedna uz drugu",
    ],
    correct: 0,
  },
  {
    id: "b20",
    topic: "kpr",
    group: "aed-deca",
    text: "Kod deteta od 1 do 8 godina koristimo AED aparat sa elektrodama koje su:",
    options: ["Iste kao i za odrasle", "Prilagođene uzrastu deteta", "Postavljene na prednju stranu grudnog koša"],
    correct: 1,
  },
  {
    id: "b21",
    topic: "disajni",
    text: "Oslobađanje disajnih puteva od stranog tela izvodi se sledećim rasporedom:",
    options: [
      "Do 10 udaraca dlanom između lopatica",
      "Do 5 udaraca između lopatica i do 5 abdominalnih pritisaka",
      "Do 3 abdominalna pritiska po Hajmlihu",
    ],
    correct: 1,
  },
  {
    id: "b22",
    topic: "disajni",
    text: "Pravilan postupak kod potpune opstrukcije disajnih puteva (zagušenja) je:",
    options: [
      "Što pre primeniti Hajmlihov hvat",
      "Primeniti do 5 udaraca dlanom između lopatica i do 5 abdominalnih pritisaka – Hajmlihov hvat",
      "Izazvati nagon na povraćanje",
    ],
    correct: 1,
  },
  {
    id: "b23",
    topic: "krvarenje",
    text: "Podela krvarenja u odnosu na vrstu povređenog krvnog suda je:",
    options: ["Arterijsko, vensko, kardijalno", "Arterijsko, vensko, kapilarno", "Spoljašnje i unutrašnje"],
    correct: 1,
  },
  {
    id: "b24",
    topic: "krvarenje",
    group: "gubitak-krvi",
    text: "Koliki gubitak krvi se klasifikuje kao SREDNJE krvarenje?",
    options: ["1 l (oko 25%) krvi", "1,5 l (od 15 do 30%) krvi", "2 l (oko 40%) krvi"],
    correct: 1,
  },
  {
    id: "b25",
    topic: "krvarenje",
    text: "Krvarenje nastaje:",
    options: [
      "Samo nakon povreda sa otvorenim ranama",
      "Nakon povreda i usled različitih bolesti",
      "Isključivo kao posledica preloma kostiju koji povređuju meka tkiva",
    ],
    correct: 1,
  },
  {
    id: "b26",
    topic: "krvarenje",
    text: "Krvni podliv (modrica) je isto što i krvni izliv. Navedeni iskaz je:",
    options: ["Tačan", "Netačan", "Nema razlike, osim ako ne postoji i oštećenje kože na mestu povrede"],
    correct: 1,
  },
  {
    id: "b27",
    topic: "krvarenje",
    text: "Pojava teškog disanja, gladi za vazduhom, poremećaj svesti, nevoljno pražnjenje creva i bešike su:",
    options: [
      "Simptomi i znaci preloma kostiju",
      "Simptomi i znaci bliske smrti od iskrvarenja",
      "Simptomi i znaci bolesti pluća",
    ],
    correct: 1,
  },
  {
    id: "b28",
    topic: "krvarenje",
    text: "Povređenog kod kojeg postoji krvarenje iz ušnog kanala postavljamo u koji položaj?",
    options: [
      "Polusedeći položaj sa glavom nagnutom na stranu koja krvari",
      "Polusedeći sa savijenim kolenima",
      "Položaj na trbuhu sa glavom okrenutom na stranu uha koje krvari",
    ],
    correct: 0,
  },
  {
    id: "b29",
    topic: "krvarenje",
    group: "amputirani-deo",
    text: "Postupak sa amputiranim delom je sledeći:",
    options: [
      "Amputirani deo nije potrebno tretirati, samo poneti u bolnicu",
      "Amputirani deo umotati u foliju, a zatim u kesu, ubeležiti vreme i transportovati",
      "Amputirani deo staviti u kesu i zatvoriti, zatim zaštititi gazom, pa staviti u posudu sa ledom, ubeležiti vreme, zatim transportovati",
    ],
    correct: 2,
  },
  {
    id: "b30",
    topic: "krvarenje",
    text: "Prilikom krvarenja iz nosa, konstantan pritisak na nozdrve treba da traje minimum:",
    options: ["Do 15 minuta", "Do 20 minuta", "Do 10 minuta"],
    correct: 2,
  },
  {
    id: "b31",
    topic: "krvarenje",
    text: "Kod osobe kod koje je nastala amputacija usled povrede nije dozvoljena upotreba Esmarhove poveske zbog:",
    options: [
      "Neadekvatne kompresije koju nije moguće kontrolisati",
      "Mogućeg oštećenja amputacionog patrljka što bi onemogućilo hiruršku rekonstrukciju",
      "Dokazanog neuspeha u zaustavljanju gubitka krvi",
    ],
    correct: 1,
  },
  {
    id: "b32",
    topic: "krvarenje",
    text: "Ako kompresivni zavoj na podlaktici prokrvari, postavlja se drugi bez skidanja prethodnog, a cirkulaciju ispod njega proveravamo:",
    options: [
      "Pipanjem pulsa iznad postavljenog zavoja",
      "Posmatranjem boje iznad postavljenog zavoja",
      "Proverom pulsa ispod mesta postavljenog zavoja, proverom boje kože i pojave trnjenja šake",
    ],
    correct: 2,
  },

  // ─────────────────────────── VERZIJA C ───────────────────────────
  {
    id: "c29",
    topic: "krvarenje",
    group: "amputirani-deo",
    text: "Postupak sa amputiranim delom je sledeći:",
    options: [
      "Amputirani deo staviti u kesu, zatim u tkaninu, pa u kesu sa ledom i ponovo u tkaninu",
      "Amputirani deo umotati u gazu, a zatim u kesu sa ledom",
      "Amputirani deo staviti u kesu, zatim u kesu sa ledom i potom u foliju ili tkaninu koja će održavati temperaturu",
    ],
    correct: 0,
  },
  {
    id: "c30",
    topic: "povrede",
    text: "Prilikom kraš povrede (povreda nagnječenja), teret se sme pomeriti sa povređenog ako je prošlo:",
    options: ["Do 15 minuta", "Do 20 minuta", "Do 30 minuta"],
    correct: 0,
  },
  {
    id: "c31",
    topic: "povrede",
    text: "Kod osobe sa otvorenim prelomom potkolenice, prvi korak u zbrinjavanju je:",
    options: [
      "Obezbediti mirovanje povređene noge",
      "Prekriti ranu gazom i previti je",
      "Postaviti osobu u položaj autotransfuzije",
    ],
    correct: 0,
  },
  {
    id: "c32",
    topic: "povrede",
    text: "RICE procedura kod povreda zglobova podrazumeva:",
    options: [
      "Repoziciju (nameštanje) zgloba, stavljanje leda ili hladne obloge, proveru cirkulacije i elevaciju",
      "Repoziciju (nameštanje) zgloba, imobilizaciju, proveru cirkulacije i elevaciju",
      "Mirovanje, stavljanje leda ili hladne obloge, kompresiju i elevaciju zgloba",
    ],
    correct: 2,
    note: "RICE = Rest (mirovanje), Ice (led), Compression (kompresija), Elevation (elevacija).",
  },
  {
    id: "c33",
    topic: "povrede",
    group: "vratna-kicma",
    text: "Ukoliko kod osobe koja je svesna sumnjamo na povredu vratnog dela kičme, osnovna mera prve pomoći je:",
    options: ["Trostruki hvat", "Manuelna stabilizacija glave", "Postavljanje improvizovanog kolira"],
    correct: 1,
  },
  {
    id: "c33b",
    topic: "povrede",
    group: "vratna-kicma",
    text: "Ukoliko kod osobe koja je svesna sumnjamo na povredu vratnog dela kičme, a ima i iščašenje skočnog zgloba leve noge, osnovna mera prve pomoći je:",
    options: [
      "Trostruki hvat, pa imobilizacija zgloba",
      "Manuelna stabilizacija glave, potom imobilizacija zgloba",
      "Postavljanje improvizovanog kolira, a potom imobilizacija zgloba",
    ],
    correct: 1,
  },
  {
    id: "c34",
    topic: "povrede",
    group: "pravilo-devetke",
    text: "Koristeći pravilo devetke, ukoliko se opekotine nalaze na celom grudnom košu, trbuhu i leđima, opečena je površina od:",
    options: ["18%", "36%", "45%"],
    correct: 1,
    note: "Pravilo devetke: grudni koš + trbuh (prednja strana trupa) = 18%, leđa = 18%. Ukupno 36%.",
  },
  {
    id: "c34b",
    topic: "povrede",
    group: "pravilo-devetke",
    text: "Koristeći pravilo devetke, ukoliko se opekotine nalaze na celoj glavi i celoj levoj nozi, opečena je površina od:",
    options: ["18%", "36%", "27%"],
    correct: 2,
    note: "Pravilo devetke: glava = 9%, cela noga = 18%. Ukupno 27%.",
  },
  {
    id: "c35",
    topic: "povrede",
    text: "Kolika površina kože je zahvaćena opekotinama drugog stepena ako se razvija stanje šoka?",
    options: ["15%", "20%", "30%"],
    correct: 1,
  },
  {
    id: "c35b",
    topic: "povrede",
    text: "Kod opekotina trećeg stepena bolovi su izuzetno jaki i zahtevaju upotrebu lekova protiv bola. Navedeni iskaz je:",
    options: ["Tačan", "Netačan", "Tačan, ako je prisutan samo treći stepen opekotina"],
    correct: 1,
    note: "Kod opekotina trećeg stepena su uništeni i nervni završeci, pa bola najčešće nema.",
  },
  {
    id: "c36",
    topic: "povrede",
    text: "Mere prve pomoći kod hemijskih opekotina podrazumevaju:",
    options: [
      "Ispiranje tekućom vodom najmanje 20 minuta, pokrivanje sterilnim materijalom i previjanje",
      "Samo uklanjanje odeće i hitno transportovanje u zdravstvenu ustanovu",
      "Ispiranje blagom bazom 10 minuta ili dok bol ne prestane, nakon toga sterilno pokrivanje i previjanje",
    ],
    correct: 0,
  },
  {
    id: "c37",
    topic: "stanja",
    text: "U koji položaj treba postaviti osobu sa srčanim udarom (infarktom)?",
    options: [
      "Sedeći položaj blago nagnut napred",
      "Sedeći položaj sa rukama oslonjenim iza leđa",
      "Polusedeći sa savijenim nogama i poduprtom glavom i ramenima",
    ],
    correct: 2,
  },
  {
    id: "c38",
    topic: "stanja",
    text: "U koji položaj postaviti osobu sa infarktom srca koja je izgubila svest?",
    options: [
      "Ležeći položaj sa podignutim nogama",
      "Bočni relaksirajući položaj",
      "Polusedeći sa savijenim nogama i poduprtom glavom i ramenima",
    ],
    correct: 1,
  },
  {
    id: "c39",
    topic: "stanja",
    text: "Kod srčanog NAPADA, mirovanje i uzimanje leka protiv bola:",
    options: ["Smanjuje bol", "Ne smanjuje bol", "Nema bitnog uticaja na bol"],
    correct: 0,
  },
  {
    id: "c40",
    topic: "stanja",
    group: "prepoznavanje-napad",
    text: "Srčani NAPAD najčešće ćemo prepoznati po sledećem:",
    options: [
      "Bol se javlja najčešće pri naporu i smanjuje se nakon mirovanja",
      "Bol se javlja iznenada u mirovanju, ali se smiruje nakon uzimanja lekova",
      "Bol se javlja iznenada, može i usled uzbuđenja, i ne smiruje se nakon uzimanja lekova",
    ],
    correct: 0,
  },
  {
    id: "c41",
    topic: "stanja",
    text: "Prilikom histeričnog napada, u okviru mera prve pomoći:",
    options: [
      "Ne obraćati pažnju na obolelog",
      "Pokazati saosećanje sa obolelim i utešiti ga do dolaska hitne medicinske pomoći",
      "Odvesti obolelog na tiho mesto, ne pokazivati preterano saosećanje i biti uz osobu sve vreme do dolaska hitne medicinske pomoći",
    ],
    correct: 2,
  },
  {
    id: "c42",
    topic: "trovanja",
    text: "Tetanus i besnilo nastaju:",
    options: [
      "Ujedom insekata",
      "Ujedom samo divljih životinja",
      "Ujedom domaćih, divljih i životinja iz zoološkog vrta",
    ],
    correct: 2,
  },
  {
    id: "c43",
    topic: "trovanja",
    text: "Trovanja mogu biti:",
    options: [
      "Zadesna i namerna",
      "Zadesna, slučajna i ubilačka",
      "Zadesna, slučajna, kriminogena i samoubilačka",
    ],
    correct: 2,
  },
  {
    id: "c44",
    topic: "stanja",
    text: "„Aura” se javlja u vezi sa napadom kod osoba koje boluju od epilepsije, a predstavlja:",
    options: [
      "Karakterističan izgled obolelog",
      "Predznak napada",
      "Poseban emotivni doživljaj nakon napada epilepsije",
    ],
    correct: 1,
  },
  {
    id: "c45",
    topic: "trovanja",
    text: "U slučaju uboda pčele u predelu glave i vrata, ukoliko osoba doživljava alergijsku reakciju, osnovna mera prve pomoći je hitno vađenje žaoke, a potom:",
    options: ["Led dati da sisa i hladan oblog na mesto uboda", "Započeti KPR", "Raditi vežbe disanja"],
    correct: 0,
  },
  {
    id: "c46",
    topic: "trovanja",
    text: "U slučaju zmijskog ujeda:",
    options: [
      "Raseći mesto ujeda i hitno transportovati u bolnicu",
      "Staviti hemostatsku povesku i hitno transportovati u bolnicu",
      "Strogo mirovanje, imobilisati ekstremitet, hladni oblozi i hitno transportovati u bolnicu",
    ],
    correct: 2,
  },
  {
    id: "c47",
    topic: "trovanja",
    text: "Neutralizaciju delovanja otrova u okviru prve pomoći sprovodimo davanjem antidota:",
    options: [
      "Davanjem vode uvek",
      "Davanjem aktivnog uglja, mleka, žestokih alkoholnih pića, belanceta, skroba i sode bikarbone",
      "Davanjem baze radi neutralizacije",
    ],
    correct: 1,
  },
  {
    id: "c48",
    topic: "trovanja",
    text: "Trovanja bazama (alkalijama) su najčešća i opasnija su nego trovanja kiselinama. Navedeni iskaz je:",
    options: ["Netačan", "Tačan", "Svaki otrov je jednako opasan"],
    correct: 1,
  },
  {
    id: "c49",
    topic: "povrede",
    text: "Znaci preloma karlice su:",
    options: [
      "Bol u donjem delu stomaka",
      "Nepravilan hod",
      "Bol i otok prepona, nemoguće/otežano stajanje i hod, zastoj mokrenja, pojava znakova unutrašnjeg krvarenja",
    ],
    correct: 2,
  },
  {
    id: "c50",
    topic: "pregled",
    text: "Kontinuirano praćenje stanja svesti podrazumeva:",
    options: [
      "Proveru vitalnih funkcija",
      "Proveru da li je osoba svesna",
      "Proveru budnosti, reakcije na govor, na bol i odsustva reagovanja povređenog/obolelog lica",
    ],
    correct: 2,
    note: "To je AVPU skala: Alert (budan), Verbal (reaguje na govor), Pain (reaguje na bol), Unresponsive (ne reaguje).",
  },

  // ─────────────────────────── VERZIJA D ───────────────────────────
  {
    id: "d07",
    topic: "pregled",
    group: "sekundarni-pregled",
    text: "Sekundarni pregled povređenog podrazumeva:",
    options: [
      "Mehanizam povređivanja, znake i simptome i detaljan pregled tela",
      "Detaljan pregled tela",
      "Detaljan pregled tela i proveru vitalnih funkcija",
    ],
    correct: 0,
  },
  {
    id: "d08",
    topic: "pregled",
    group: "znaci-simptomi",
    text: "U SIMPTOME spadaju:",
    options: [
      "Bol, žeđ, crvenilo, vrtoglavica",
      "Zujanje u ušima, mučnina, vrtoglavica, slabost",
      "Svetlucanje pred očima, hladnoća, bledilo, vrtoglavica",
    ],
    correct: 1,
    note: "Simptomi su ono što povređeni OSEĆA i opiše. Crvenilo i bledilo su znaci — njih spasilac vidi.",
  },
  {
    id: "d09",
    topic: "pregled",
    group: "kaciga",
    text: "Zaštitna kaciga se SKIDA kod povređenog u slučaju:",
    options: [
      "Kada disajni put ne možemo učiniti prohodnim sa kacigom na glavi",
      "Kada motociklista leži na stomaku",
      "Kada motociklista diše brže od 18 ciklusa u minuti",
    ],
    correct: 0,
  },
  {
    id: "d10",
    topic: "pregled",
    text: "Kod zdrave, odrasle osobe puls u miru iznosi:",
    options: ["50 do 100 otkucaja u minutu", "80 do 100 otkucaja u minutu", "60 do 80 otkucaja u minutu"],
    correct: 2,
  },
  {
    id: "d11",
    topic: "pregled",
    text: "Normalan broj udisaja u mirovanju kod odrasle osobe je:",
    options: ["10 do 12 u minutu", "12 do 16 u minutu", "15 do 20 u minutu"],
    correct: 1,
  },
  {
    id: "d12",
    topic: "pregled",
    group: "zavojni-materijal",
    text: "Šta od navedenog SPADA u sterilan zavojni materijal?",
    options: [
      "Sterilna gaza, prvi zavoj i kaliko zavoj",
      "Sterilna gaza, prvi zavoj za trbuh i prvi zavoj",
      "Sterilna gaza, prvi zavoj i fabrički zapakovan elastični zavoj",
    ],
    correct: 1,
  },
  {
    id: "d13",
    topic: "kpr",
    group: "uzrok-zastoja",
    text: "Najčešći uzrok naglog srčanog zastoja je/su:",
    options: ["Srčana oboljenja", "Udar struje ili groma", "Zagušenje"],
    correct: 0,
  },
  {
    id: "d14",
    topic: "kpr",
    group: "znaci-zastoja",
    text: "Osnovni znaci naglog srčanog zastoja su:",
    options: ["Odsustvo svesti i disanja", "Odsustvo disanja i pulsa", "Odsustvo svesti i pulsa"],
    correct: 0,
  },
  {
    id: "d15",
    topic: "kpr",
    group: "odnos-kompresija",
    text: "Kompresije grudnog koša i veštačko disanje se rade u odnosu:",
    options: ["15:2", "30:2", "15:1"],
    correct: 1,
  },
  {
    id: "d16",
    topic: "kpr",
    group: "brzina-masaze",
    text: "Spoljašnja masaža srca izvodi se ritmično, brzinom od:",
    options: ["60 do 80 u minutu", "80 do 100 u minutu", "100 do 120 u minutu"],
    correct: 2,
  },
  {
    id: "d17",
    topic: "kpr",
    group: "polozaj-glave",
    text: "U koji položaj treba postaviti glavu BEBE (do 12 meseci) prilikom veštačkog disanja?",
    options: ["U neutralan položaj", "Zabačenu unazad", "Zatečeni položaj"],
    correct: 0,
  },
  {
    id: "d18",
    topic: "kpr",
    group: "aed-funkcije",
    text: "Osnovne dve funkcije AED aparata su:",
    options: [
      "Analiziranje srčanog ritma i davanje glasovnih instrukcija",
      "Analiziranje srčanog ritma i emitovanje elektrošokova",
      "Davanje glasovnih instrukcija i emitovanje elektrošokova",
    ],
    correct: 1,
  },
  {
    id: "d19",
    topic: "kpr",
    group: "aed-elektrode",
    text: "Kod odrasle osobe, elektrode AED aparata se postavljaju:",
    options: [
      "Na sredinu grudnog koša i na sredinu leđa, između lopatica",
      "Na gornji desni ugao grudnog koša ispod ključne kosti i pored leve bradavice, s bočne strane grudnog koša",
      "Na gornji levi ugao grudnog koša ispod ključne kosti i pored desne bradavice, s bočne strane grudnog koša",
    ],
    correct: 1,
  },
  {
    id: "d20",
    topic: "kpr",
    group: "aed-deca",
    text: "U slučaju srčanog zastoja kod deteta uzrasta 10 godina primenjuje se:",
    options: ["Standardni AED aparat", "Specijalni AED aparat", "Standardni AED aparat sa prilagođenim elektrodama"],
    correct: 0,
  },
  {
    id: "d21",
    topic: "disajni",
    text: "Svrha postavljanja osobe u bočni položaj je:",
    options: [
      "Da se disajni put drži prohodnim i da se omogući oticanje tečnog sadržaja iz usta",
      "Da povređeni bude u stabilnom položaju i da se spreči dalje povređivanje",
      "Da se otvori disajni put i olakša transport povređenog",
    ],
    correct: 0,
  },
  {
    id: "d23",
    topic: "disajni",
    text: "Kod osobe koja ima opstrukciju (zagušenje) gornjih disajnih puteva i koja je izgubila svest, primenićemo:",
    options: ["Grudne kompresije i ventilaciju", "Samo grudne kompresije", "Modifikovan Hajmlihov hvat"],
    correct: 0,
  },
  {
    id: "d24",
    topic: "krvarenje",
    group: "gubitak-krvi",
    text: "Koliki gubitak krvi može dovesti do stanja ŠOKA?",
    options: ["1 l (oko 25%) krvi", "1,5 l (oko 30%) krvi", "2 l (oko 40%) krvi"],
    correct: 1,
  },
  {
    id: "d25",
    topic: "krvarenje",
    text: "Najefikasniji metod za zaustavljanje krvarenja na nozi u okviru prve pomoći je:",
    options: ["Elevacija noge", "Primena pritiska na tačke digitalne kompresije", "Kompresivni zavoj"],
    correct: 2,
  },
  {
    id: "d26",
    topic: "krvarenje",
    text: "U koji položaj postavljamo osobu u stanju iskrvarenosti (šoka)?",
    options: ["Ležeći na boku", "Položaj autotransfuzije", "Ležeći sa izdignutom glavom i ramenima"],
    correct: 1,
  },
  {
    id: "d27",
    topic: "krvarenje",
    text: "Da li je dozvoljeno poveskom zaustaviti krvarenje u okviru laičke prve pomoći?",
    options: ["Da", "Ne", "Da, ako je u pitanju teška povreda npr. amputacija"],
    correct: 1,
  },
  {
    id: "d28",
    topic: "krvarenje",
    text: "Povređenog kod kojeg sumnjamo na unutrašnje krvarenje (trbuha) postavljamo u koji položaj?",
    options: ["Ležeći sa uzdignutom glavom i ramenima", "Polusedeći sa savijenim kolenima", "Položaj autotransfuzije"],
    correct: 2,
  },
  {
    id: "d37b",
    topic: "stanja",
    text: "U koji položaj treba postaviti osobu sa astmatičnim napadom?",
    options: [
      "Sedeći položaj blago nagnut napred",
      "Sedeći položaj sa rukama oslonjenim iza leđa",
      "Polusedeći sa savijenim nogama",
    ],
    correct: 0,
  },
  {
    id: "d38b",
    topic: "stanja",
    text: "U koji položaj postaviti osobu sa alergijskim šokom zbog uboda insekta, koja je svesna, diše, nema mučninu ni vrtoglavicu?",
    options: ["Ležeći položaj sa podignutim nogama", "Sedeći položaj", "Polusedeći sa savijenim nogama"],
    correct: 2,
  },
  {
    id: "d39b",
    topic: "stanja",
    text: "U odnosu na trajanje tegoba, srčani NAPAD uobičajeno traje:",
    options: ["Do 20 minuta", "Do 30 minuta", "Duže od 30 minuta"],
    correct: 0,
  },
  {
    id: "d40b",
    topic: "stanja",
    group: "prepoznavanje-napad",
    text: "INFARKT srca ćemo prepoznati po sledećem:",
    options: [
      "Bol se javlja pri naporu i smanjuje se nakon mirovanja",
      "Bol se javlja iznenada, u miru, ali se smiruje nakon uzimanja leka",
      "Bol se javlja iznenada, u miru, i ne smiruje se nakon uzimanja leka",
    ],
    correct: 2,
  },
  {
    id: "d41b",
    topic: "stanja",
    text: "Kod kog stanja dah može mirisati na aceton?",
    options: ["Hipoglikemije", "Hiperglikemije", "Epilepsije"],
    correct: 1,
  },
  {
    id: "d42b",
    topic: "stanja",
    text: "Osnovna mera prve pomoći kod nesvestice je:",
    options: [
      "Postaviti povređenog u ležeći položaj sa podignutim nogama",
      "Podići povređenog i postaviti ga da sedne",
      "Umiti povređenog i dati mu šećer",
    ],
    correct: 0,
  },

  // ─────────── VERZIJA E (dopunski list, tačni odgovori sa crvenom oznakom) ───────────
  {
    id: "e01",
    topic: "pristup",
    text: "Osnovna 4 cilja prve pomoći su:",
    options: [
      "Očuvati svest, otvoriti disajni put, očuvati puls i zaustaviti krvarenje",
      "Spasiti život, obavestiti hitne službe, pružiti psihološku prvu pomoć i negu povređenog",
      "Spasiti život, sprečavanje daljeg pogoršanja stanja, ubrzanje izlečenja i smanjenje invalidnosti",
    ],
    correct: 2,
  },
  {
    id: "e02",
    topic: "pristup",
    text: "Nakon procene situacije, koji je prvi sledeći korak u postupku na mestu nesreće?",
    options: [
      "Bezbednost spasioca i povređenog",
      "Poziv hitnim službama",
      "Pružanje neodložnih mera pomoći",
    ],
    correct: 0,
  },
  {
    id: "e03",
    topic: "pristup",
    group: "znak-na-fotografiji",
    plate: { top: "30", bottom: "1202" },
    text: "Koji znak se nalazi na fotografiji iznad?",
    options: [
      "Oznaka za broj auto i moto puteva",
      "Specijalna oznaka za transport opasnih materija",
      "Specijalna oznaka za opasnost od trovanja",
    ],
    correct: 1,
    note: "Narandžasta tablica na vozilu: gornji broj je oznaka opasnosti, donji je UN broj materije (1202 = dizel gorivo).",
  },
  {
    id: "e04",
    topic: "pristup",
    text: "Požarni trougao čine:",
    options: [
      "Plamen, vazduh i kiseonik",
      "Gorivi materijal, strujanje vazduha i kiseonik",
      "Kiseonik, varnica i gorivi materijal",
    ],
    correct: 2,
  },
  {
    id: "e05",
    topic: "pristup",
    group: "voltin-luk",
    text: "Struja visokog napona oslobođena iz oštećenih vodova može se u vidu luka (Voltin luk) širiti na udaljenosti od:",
    options: ["9 metara", "18 metara", "27 metara"],
    correct: 1,
  },
  {
    id: "e06",
    topic: "pregled",
    group: "primarni-pregled",
    text: "Primarni pregled povređenog podrazumeva proveru:",
    options: [
      "Svesti, prohodnosti disajnog puta i disanje",
      "Svesti, glave i vrata i disanja",
      "Svesti, disanja i pulsa",
    ],
    correct: 0,
  },
];

export const QUESTION_BY_ID = new Map(QUESTIONS.map((q) => [q.id, q]));

export const TOTAL_QUESTIONS = QUESTIONS.length;
